### ISSUE TITLE
build and test for .net

### ISSUE THREAD

**Issue by csavarabigel** [BME-MIT-IET/iet-hf2021-gitgud#20]
-maven build for java is not compatible
-delete pom.xml
-new build file needed instead of maven.yml

**Comment by annagerse** [comment]
On it!

**Comment by annagerse** [comment]
Deleted the two files, please make the new build file

**Comment by csavarabigel** [comment]
-I created a new workflow for .net build
-got an error for the specified version

**Comment by annagerse** [comment]
I completed the build file with msbuild and NuGet, but the build failed in 15 minutes, with no warnings or errors. Please help me.

**Comment by csavarabigel** [comment]
I removed the --no build from dotnet test
Build was ok, but 1 test failed

**Comment by annagerse** [comment]
Thanks for the work, the build is up and running!
