### ISSUE TITLE
build with maven

### ISSUE THREAD

**Issue by csavarabigel** [BME-MIT-IET/iet-hf2021-gitgud#4]
create maven.yml file and build project

**Comment by annagerse** [comment]
Okay, I will make the maven.yml

**Comment by annagerse** [comment]
Maven.yml run failed, because the pom.xml file is missing. Please fix.
Link to the error message: https://github.com/BME-MIT-IET/iet-hf2021-gitgud/runs/2527589656?check_suite_focus=true

**Comment by csavarabigel** [comment]
I will create the pom.xml file

**Comment by annagerse** [comment]
Thanks, I'll make the maven file then!

**Comment by annagerse** [comment]
Maven ran successfully, review needed

**Comment by ptomi98** [comment]
Review done. Successfully working.

**Comment by annagerse** [comment]
Pull request merged and I'm now closing this Issue.
